[platformio]
default_envs = maestro, esclavo, repetidor

[env:maestro]
platform = ststm32
board = genericSTM32F103C8
framework = arduino
upload_protocol = stlink
upload_command = "C:\Program Files\STMicroelectronics\STM32Cube\STM32CubeProgrammer\bin\STM32_Programmer_CLI.exe" --connect port=swd reset=HWrst --write "$SOURCE" -rst
lib_deps = olikraus/U8g2@^2.35.19
build_flags = -D ROL_MAESTRO
build_src_filter = +<*> -<esclavo.cpp> -<repetidor.cpp>

[env:esclavo]
platform = ststm32
board = genericSTM32F103C8
framework = arduino
upload_protocol = stlink
upload_command = "C:\Program Files\STMicroelectronics\STM32Cube\STM32CubeProgrammer\bin\STM32_Programmer_CLI.exe" --connect port=swd reset=HWrst --write "$SOURCE" -rst
lib_deps = olikraus/U8g2@^2.35.19
build_flags = -D ROL_ESCLAVO
build_src_filter = +<*> -<maestro.cpp> -<repetidor.cpp> -<lcd.cpp> -<botones.cpp> -<coordinador.cpp> -<menu.cpp> -<modo_*.cpp>

[env:repetidor]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
build_src_filter = -<*> +<repetidor.cpp>